# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 461c75a9e78aba7b6d5dbcb7cc8b3bc90b4b9a53e6d4bb3718886e805baad900dd5dd0810ef3c9122042e1094ab4a714f0d56cbc0cb58148e7d51d5de95efa64

test:
  secret_key_base: 43739067cdb78f106876f09a76cb4c487d1efb5873ef83372f49c988211515823d9a58c244fbb30a79b3614d106d6f15a0c82eced11db7f00edbad923b1cb453

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
